version: "3.8"

services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    hostname: db
    container_name: db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 1s
      timeout: 30s

  app:
    build:
      context: app
    ports:
      - "8888:8888"
    depends_on:
      db:
        condition: service_healthy